# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="/Users/fanding/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS=true

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
# 追加内容
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.bash_profile
alias QQ='open /Applications/QQ.app'
alias workdir='cd /Users/fanding/spiderCode/spider-python'
alias spidertest='cd /Users/fanding/spiderCode/spiderTest'
alias sph='tmux split-pane -h'
alias spv='tmux split-pane -v'
alias s='tmux  select-pane -t'
alias tn='tmux new -s'
alias td='tmux detach'
alias ta='tmux attach-session -t'
alias tk='tmux kill-session -t'
alias tl='tmux ls'
alias sru='ssh ubuntu@52.81.63.75'
alias sr='ssh root@52.81.63.75'
alias sw='ssh work@52.81.63.75'
alias tm='tldr'
alias notebook='python -m IPython notebook'
alias tmsize='du -sh'
alias db='mysql -uroot -p102487'
alias cdflink='cd /usr/local/Cellar/apache-flink/1.8.1'
alias f='fuck'
alias imgcat='/Users/fanding/mybin/imgcat'
alias apktool='/Users/fanding/mybin/apktool'
alias localmysql='mysql -u root -p102487 --auto-rehash'

eval $(thefuck --alias)
export PATH="/usr/local/opt/maven@3.3/bin:$PATH"


# appium config
#android sdk
export ANDROID_HOME=~/Library/Android/sdk
export PATH="$HOME/.yarn/bin:$PATH"
#java_home
export JAVA_HOME=$(/usr/libexec/java_home)
export PATH=$JAVA_HOME/bin:$PATH
export CLASS_PATH=$JAVA_HOME/lib


export JAVA_HOME=$(/usr/libexec/java_home)
export ANDROID_HOME=/usr/local/android-sdk-macosx

# 腾讯云
alias ct='ssh ubuntu@49.233.143.57'

# git
alias gs='git status .'
alias gd='git diff'
alias gc='git checkout'
alias ga='git add'
alias gma='git commit -m "add"'
alias gmu='git commit -m "update"'
alias gp='git push origin master'
alias gclean='git clean -d -fx'

# proxy
export http_proxy=http://127.0.0.1:1087;export https_proxy=http://127.0.0.1:1087;

# 常用字符串
alias fanding='echo "![gongzonghao](https://github.com/fandsimple/src/blob/master/img/wx.jpeg)\n![gongzonghao](https://github.com/fandsimple/src/blob/master/img/gongzonghao.jpeg)"'
